### ISSUE TITLE
Red Screen (of death?) when open the application.

### ISSUE THREAD

**Issue by netoeuler** [spheras/messic#118]
I just install Messic by the DEB Package in Debian 8 64 bits, show a screen to select the folder and after that show a red screen. I close the application, open again and the red screen was there again.

![screenshot from 2016-03-18 09 49 02](https://cloud.githubusercontent.com/assets/3870633/13878223/ad97933c-ecee-11e5-9a32-73394ea86f36.png)

So I start to click and move the cursos around the screen I show some buttons when the cursos pass over there.

![screenshot from 2016-03-18 09 48 49](https://cloud.githubusercontent.com/assets/3870633/13878241/c58b320a-ecee-11e5-8cf6-b9b52ac16972.png)

**Comment by spheras** [comment]
Wow! this is the first time I see that! the red color is the background of the JFrame window (i don't know why I choosed red :D). You should see the components and a background image over this color.
Currently I work on an elementary OS (x64) distribution perfectly. I've checked as well on Ubuntu and Centos time ago.
Is it possible for you to see the java console log? anyway I will download a Debian 8 iso to check what's happening there during this weekend.  I will let you know if I discover what's hapenning.

Thanks for reporting this!

**Comment by spheras** [comment]
@netoeuler what flavour are you using for debian 8?  gnome, kde, lxde, mate, xfce

**Comment by israbr** [comment]
I saw the same in my machine (Ubuntu x64 with Gnome3) after installing the
DEB package. That's why I asked for the Jar one (from the .tar.gz) which
runs perfectly

**Comment by spheras** [comment]
:open_mouth: that's surprising @israbr 
The only difference (basically) between both versions is just the automated process unzipping the .tar.gz and shortcuts installations.  I'll do some checks.
@netoeuler could you check if the .gz version works?

**Comment by spheras** [comment]
I installed messic (deb versoin) in my laptop and is working perfectly (elementary os freya - gnome 3). I will download the last ubuntu gnome version and check

**Comment by netoeuler** [comment]
@spheras I'm using Gnome. I try to install with .gz but I can't, probably because uses Java 8 and I have the 7 installed. I try to execute pointing Java to the 7 but show another error.

> error: Class names, 'org.messic.starter.Starter', are only accepted if annotation processing is explicitly requested

I searched and see that put .java in the end of class resolves but doesn't work in this case.

**Comment by spheras** [comment]
I've just installed the last ubuntu gnome version. It is red!! Oh my god!! @israbr it is the same if the installed is .deb or not .gz. Did you say that the GZ version was OK??

**Comment by israbr** [comment]
For me the .deb didn't work but the .gz DID work. I uncompressed the
tar.gz, cd into bin/, run the .sh file (can't remember the name of the
script though) and it worked like a charm

**Comment by spheras** [comment]
Ok, finally I discovered the bug.  It seems a problem/bug of java jframe with gnome3 (probably the gtk version?). The function setUndecorated of jFrame is the guilty. When you setUndecorated(true) the jframe, the base window is not displayed until other events happens and repaint each component (for example when a mouseover event or similar)

I have been searching on the internet and someone said that forcing the jframe to resize after displaying the window is enough, and that's true.  This workaround fix the problem:
        frame.setSize(frame.getWidth()-1, frame.getHeight());

So, I will investigate a bit more to see other ways to solve it, but probably I will put this hack into the code to solve the problem in messic 1.1.0 (which is expected to be delivered next week).

@netoeuler thanks a lot for reporting this problem. Unfortunately I don't see the way to fix the problem in the current stable version (1.0.1) and I think it doesn't make sense to create a revision of the 1.0.1  due to the new version 1.1.0 will be delivered next week. Hope you can wait until then (or move the mouse around to find the start service button and launch it, at the end it is only a render problem of the window :D)

thanks!

**Comment by netoeuler** [comment]
Hahaha! I'll do this until release a new version so. :D
No problem, I'm here to contribute in what be necessary.

**Comment by spheras** [comment]
great! :D As you see we need a lot of help, you are more than welcome.
I close the issue.
