### ISSUE TITLE
Show current title song and album in browser tab's name

### ISSUE THREAD

**Issue by ruayrod** [spheras/messic#125]
To avoid having to be looking at the name of a song or album that you're playing if you are in another browser tab, you could put in the title of the browser tab.

For example:
1. When stopped:
messic
2. When playing (2 samples):
messic is playing: Michael Jackson - Thriller
messic - Thriller - Michael Jackson

In spanish:
Para no tener que estar mirando el nombre de la canción o álbum que estás reproduciendo si estás en otra pestaña del navegador, por ejemplo ahora que estoy escribiendo esto, se podría poner en el titulo de la pestaña del navegador.

Por ejemplo:
1.- Cuando está parado:
messic
2.- Cuando esté reproduciendo (2 ejemplos):
messic está reproducciendo: Michael Jackson - Thriller
messic - Thriller - Michael Jackson

**Comment by spheras** [comment]
Yes, I love this idea! Do you think I could add this to the 1.1.0 version (it is practically closed to be delivered)?? but it seems very simple and useful!!!
thanks a lot!!, I will take a look to this right now

**Comment by spheras** [comment]
@ruayrod, you can see that I added this functionality.  It will be for this release (1.1.0). I hope to deliver it officially this week.
the only difference is that i couldnt add the string "is playing..." because it is a bit problematic to add this due to the multilenguage. Anyway, you can see messic - authorname - albumname - songname

Thanks again for this great idea!

**Comment by israbr** [comment]
Sorry to add anything to a closed issue but shouldn't it be better if the songname was the first after messic:
messic - songame - authorname - albumname
If you have loads of tabs open, the space for the window title is tiny hence; hence showing the title as soon as posible.

Just my 2 cts.

**Comment by ruayrod** [comment]
Sorry. I suggest:
messic - songname - authorname

Albumname isn't necessary and you can see it click tab..
Less is more... But it's only my personal opinion.

**Comment by spheras** [comment]
mmmm to be honest, I would like to put the album name too (for me sometimes is the most important). @ruayrod  why you think albumname is not important?

What do you think if:
messic »  songname - authorname [albumname]

I mean, the album name will be the last and is very very probably that it will not be seen due to the small space (only if you put the mouse over the tab).  For me is at least a possibility to see quickly the album name where is the song placed (in my case is easy to identify the author usually, but not the album)

**Comment by ruayrod** [comment]
Ok. This is only a personal opinion. You're the Master, i'm only a little padawan.
messic » songname - authorname [albumname]
It's a good option. ;)
